### PR TITLE
0.4.0: Use rustls 0.11, webpki-roots 0.13, and update other deps.

### PR DESCRIPTION
**Pull request by briansmith**
This won't build until Rustls 0.11 is released, which is being tracked here: https://github.com/ctz/rustls/pull/99

### CODE REVIEW

**Comment by quininer** [comment]
SNI seems to break the `.danger_connect_async_without_providing_domain_for_certificate_verification_and_server_name_indication()`, is this expected behavior?

**Comment by briansmith** [comment]
/cc @ctz

@quininer Thanks for pointing that out. I had not run the test suite with the "danger" feature enabled. AFAICT, that this now fails is not surprising. It is surprising it worked before.

AFAICT, Rustls doesn't support passing an empty string as the host name; you must pass a full DNS Name. Rustls should probably check its syntax and abort, but it doesn't. Instead, it generates a ClientHello that has an SNI extension with an empty hostname, which AFAICT from reading RFC 6066 is malformed and thus illegal. My recent changes regarding SNI handing in Rustls now detect this malformed SNI and the server rejects it. This is definitely intended behavior as I wrote code specifically to do this.

If we want Rustls to be able to work without providing a hostname then Rustls needs to be changed to recognize when a hostname isn't provided. At least, Rustls needs to avoid adding the SNI extension to the client hello when there is no hostname provided. I suggest doing this not by recognizing "" as "no host name", but by using a different type to explicitly opt into no-host-name behavior.

BTW, I think that even if you want to support a dangerous "no certificate validation" API, you probably should include the target DNS name in the SNI extension when it is known, because some servers will route the request completely differently in the no-SNI case vs. the SNI-provided case. In other words, you probably want to have multiple APIs:

* I have an DNS Name and I want to validate the certificate against it (the current default mode) and provide SNI.
* I have an IP address and I want to validate the certificate against the IP address (not supported by Rustls or webpki yet.)
* I have a DNS Name but I don't want to validate the certificate against the name, however I do want to still provide SNI. You could implement this on top of the current Rustls, but it is different than your current "danger" feature.
* I don't want to validate the certificate against any name, and I don't want to provide SNI. Not yet supported by Rustls because it always includes SNI in the client hello.

**Comment by quininer** [comment]
You make sense, I am not opposed to add more api.

**Comment by briansmith** [comment]
I've had another thought.

First, what's the purpose of this crate? I believe the singular purpose of this crate should be to integrate Tokio and Rustls. Therefore, any feature that isn't about making Rustls work nicely with Tokio should be assumed a priori to be out of scope.

In particular, IMO it is out of scope for tokio-rustls to provide APIs to control SNI behavior. Instead, the application should configure Rustls's SNI behavior using Rustls's configuration APIs, and pass the configuration to tokio-rustls. Similarly, it is out of scope for tokio-rustls to provide APIs to control the certificate validation behavior. Instead, the application should configure certificate validation using Rustls's APIs. Perhaps there should be a crate that makes it convenient to do "dangerous" certificate validation, but IMO that shouldn't be tokio-rustls, but a different one.

Along these line's, I'll update this PR with a commit that removes the functionality that this PR breaks, because I think this functionality should be out of scope for this library.

WDYT?

**Comment by quininer** [comment]
In fact this api comes from [tokio-tls](https://github.com/tokio-rs/tokio-tls/blob/master/src/lib.rs#L106), and I think we should keep api similar to tokio-tls.

**Comment by briansmith** [comment]
> In fact this api comes from tokio-tls, and I think we should keep api similar to tokio-tls.

I understand that's the goal, but IMO the tokio-tls API should be changed too along similar lines. I filed https://github.com/tokio-rs/tokio-tls/issues/32 for that.

**Comment by briansmith** [comment]
I submitted #15 to remove the `danger` API. I suggest that we release 0.4 without the `danger` API and re-evaluate what to do later. In particular, *ring* 0.12 contains fixes for build breakage for rustc 1.20 (IIUC) and so it would be good to have a tokio-rustls that can use *ring* 0.12 so that we have something that works on the upcoming stable release of rustc that will be released in a couple of days.

**Comment by quininer** [comment]
I decided to release 0.4, thanks for your work.

**Pull request merged**
